export const breakdownFields = {
  emergency: { label: "مصدومیت، آتش، دود شدید یا نشت سوخت وجود دارد؟", options: [["yes", "بله"], ["no", "خیر"], ["unknown", "مطمئن نیستم"]] },
  location: { label: "وضعیت محل توقف", options: [["safe", "خارج از جریان عبور و با فضای مناسب"], ["traffic", "داخل خط عبور یا کنار ترافیک خطرناک"], ["unknown", "ایمنی محل مشخص نیست"]] },
  symptom: { label: "مهم‌ترین نشانه‌ای که دیده‌اید", options: [["no-start", "استارت نمی‌خورد یا روشن نمی‌شود"], ["flat-tire", "پنچری یا آسیب لاستیک"], ["overheat", "دما بالا رفته یا بخار دیده می‌شود"], ["oil-brake", "هشدار روغن / ایراد ترمز یا فرمان"], ["check-flashing", "چراغ چک چشمک‌زن یا لرزش شدید"], ["check-steady", "چراغ چک ثابت"], ["collision", "تصادف یا آسیب چرخ و بدنه"], ["fuel", "احتمال تمام‌شدن سوخت"], ["other", "نشانه دیگر یا علت نامشخص"]] },
} as const;
export type BreakdownInput = { [Key in keyof typeof breakdownFields]: (typeof breakdownFields)[Key]["options"][number][0] };
export type BreakdownAdvice = { priority: "emergency" | "safety-first" | "stop-and-assess" | "inspection"; title: string; actions: string[]; avoid: string; servicePath?: string; serviceTitle?: string };

export function guideBreakdown(input: BreakdownInput): BreakdownAdvice {
  for (const key of Object.keys(breakdownFields) as (keyof BreakdownInput)[]) {
    if (!breakdownFields[key].options.some(([value]) => value === input[key])) throw new Error(`invalid_${key}`);
  }
  if (input.emergency === "yes") return { priority: "emergency", title: "خدمات اضطراری عمومی مقدم بر امداد خودرو هستند", actions: ["با خدمات نجات، اورژانس یا آتش‌نشانی متناسب با خطر تماس بگیرید؛ تماس با شرکت حمل جای آن‌ها را نمی‌گیرد.", "بدون واردشدن به جریان عبور، سرنشینان را از خطر دور نگه دارید و دستور مسئولان صحنه را دنبال کنید.", "هماهنگی حمل فقط پس از ارزیابی و ایمن‌شدن صحنه انجام شود."], avoid: "خودرو را روشن نکنید، به نشتی نزدیک نشوید و برای عکس، علامت‌گذاری یا تعمیر وارد مسیر عبور نشوید." };
  if (input.emergency === "unknown" || input.location !== "safe") return { priority: "safety-first", title: "اول وضعیت خطر و محل توقف را روشن کنید", actions: ["ایمنی محل در این پاسخ تأیید نشده است. اگر خطر فوری یا انسداد مسیر وجود دارد، ابتدا پلیس و خدمات اضطراری مربوط را مطلع کنید.", "نام مسیر، جهت حرکت و نزدیک‌ترین نشانه قابل تشخیص را از محل امن اعلام کنید.", "پیش از انتخاب تعمیر در محل یا حمل، امکان توقف امن متخصص باید بررسی شود."], avoid: "برای تعویض چرخ، بازدید زیر خودرو یا گذاشتن علامت وارد جریان عبور نشوید؛ هنگام رانندگی از این ابزار استفاده نکنید." };
  const choices: Record<BreakdownInput["symptom"], Omit<BreakdownAdvice, "priority"> & { priority: BreakdownAdvice["priority"] }> = {
    "no-start": { priority: "inspection", title: "بررسی برق، باتری و سامانه استارت", actions: ["بگویید استارت اصلاً نمی‌چرخد، کند می‌چرخد یا موتور می‌چرخد ولی روشن نمی‌شود.", "مدل خودرو، سابقه تعویض باتری و روشن‌ماندن چراغ‌ها را اعلام کنید؛ این نشانه‌ها خرابی باتری را قطعی نمی‌کنند."], avoid: "اتصال کابل نامطمئن، استارت پی‌درپی و تعویض باتری بدون تست توصیه نمی‌شود.", servicePath: "/services/roadside-assistance", serviceTitle: "هماهنگی بررسی خودرو در محل" },
    "flat-tire": { priority: "stop-and-assess", title: "بررسی تایر، زاپاس و فضای تعویض چرخ", actions: ["وجود زاپاس سالم، کلید قفل رینگ و وضعیت رینگ یا دیواره تایر را اعلام کنید.", "متخصص باید محل استقرار جک و امکان تعویض چرخ را بررسی کند؛ گاهی حمل، جای تعمیر کنار راه را می‌گیرد."], avoid: "با تایر خوابیده یا آسیب‌دیده ادامه ندهید و زیر خودرویی که فقط روی جک است نروید.", servicePath: "/services/flat-tire", serviceTitle: "پنچرگیری و تعویض لاستیک در محل" },
    "overheat": { priority: "stop-and-assess", title: "توقف ایمن و بررسی داغ‌کردن خودرو", actions: ["در محل امن توقف کنید و مطابق هشدارهای دفترچه عمل کنید؛ ادامه مسیر را تا ارزیابی ایمنی فرض نکنید.", "متن هشدار، بخار، نشتی قابل مشاهده از فاصله امن و زمان شروع را به مکانیک بگویید."], avoid: "درپوش رادیاتور یا مخزن تحت فشارِ داغ را باز نکنید و روی موتور داغ آب سرد نریزید.", servicePath: "/services/mobile-mechanic", serviceTitle: "هماهنگی مکانیک یا حمل پس از ارزیابی" },
    "oil-brake": { priority: "stop-and-assess", title: "ادامه رانندگی را مجاز فرض نکنید", actions: ["برای هشدار فشار روغن یا تغییر ترمز و فرمان، در اولین موقعیت امن توقف کنید.", "نوع هشدار و رفتار خودرو باید پیش از حرکت دوباره بررسی شود؛ حمل ممکن است لازم باشد."], avoid: "هشدار فشار روغن را با یادآور سرویس اشتباه نگیرید و با ترمز یا فرمان معیوب حرکت آزمایشی نکنید.", servicePath: "/services/flatbed-carrier", serviceTitle: "بررسی نیاز به حمل خودرو" },
    "check-flashing": { priority: "stop-and-assess", title: "چراغ چک چشمک‌زن یا لرزش شدید نیازمند بررسی فوری است", actions: ["در موقعیت امن توقف و شرح علائم را برای متخصص آماده کنید.", "کدها و وضعیت ثبت آن‌ها باید همراه نشانه‌های واقعی بررسی شوند؛ کد تنها قطعه خراب را تعیین نمی‌کند."], avoid: "برای خاموش‌شدن چراغ، کد را پاک نکنید و رانندگی آزمایشی پرفشار انجام ندهید.", servicePath: "/services/mobile-diagnostics", serviceTitle: "دیاگ و بررسی فنی در محل" },
    "check-steady": { priority: "inspection", title: "کد خطا و نشانه‌های خودرو را ثبت کنید", actions: ["متن هشدار و هر تغییر صدا، توان یا دما را به متخصص اعلام کنید.", "چراغ ثابت به‌تنهایی مجوز ادامه رانندگی یا تشخیص قطعی نیست؛ دفترچه همان مدل و ارزیابی فنی ملاک‌اند."], avoid: "پاک‌کردن کد یا تعویض سنسور از روی نام خطا، جای عیب‌یابی را نمی‌گیرد.", servicePath: "/services/mobile-diagnostics", serviceTitle: "هماهنگی دیاگ سیار" },
    collision: { priority: "stop-and-assess", title: "ارزیابی صحنه و انتخاب تجهیزات حمل", actions: ["ابتدا الزامات پلیس و ایمنی صحنه را رعایت کنید.", "وضعیت چرخ‌ها، فرمان، نشتی و نوع قوای محرکه را پیش از اعزام اعلام کنید."], avoid: "خودرو آسیب‌دیده را برای امتحان حرکت ندهید؛ در مدل برقی یا هیبریدی به کابل‌ها و اجزای ولتاژ بالا نزدیک نشوید.", servicePath: "/services/flatbed-carrier", serviceTitle: "هماهنگی خودروبر متناسب با آسیب" },
    fuel: { priority: "inspection", title: "ابتدا تمام‌شدن سوخت را از خرابی دیگر جدا کنید", actions: ["مقدار سوخت، نوع سوخت مجاز و رفتار خودرو قبل از توقف را اعلام کنید.", "وجود سوخت در باک، مشکل پمپ یا برق را رد نمی‌کند؛ پس از ارزیابی خدمت انتخاب می‌شود."], avoid: "با ظرف نامناسب سوخت جابه‌جا نکنید و نزدیک خودرو از شعله یا سیگار استفاده نکنید.", servicePath: "/services/fuel-delivery", serviceTitle: "بررسی امکان سوخت‌رسانی" },
    other: { priority: "inspection", title: "شرح نشانه، پیش از انتخاب قطعه یا وسیله حمل", actions: ["زمان شروع، صدای غیرمعمول، متن هشدار و آخرین تعمیر را کوتاه توضیح دهید.", "دستورالعمل مدل و بازدید متخصص تعیین می‌کنند تعمیر در محل ممکن است یا حمل لازم است."], avoid: "از این خروجی تشخیص قطعی یا اجازه ادامه حرکت برداشت نکنید.", servicePath: "/services/roadside-assistance", serviceTitle: "هماهنگی بررسی اولیه" },
  };
  return choices[input.symptom];
}
