import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/home/home-ui";
import { SeoBreadcrumbs } from "@/components/seo/seo-breadcrumbs";
import { StructuredData } from "@/components/seo/structured-data";
import { SubpageShell } from "@/components/site/subpage-shell";
import { businessFacts } from "@/content/business";
import { breadcrumbSchema, webPageSchema } from "@/seo/schemas";
import { seoMetadata } from "@/seo/metadata";

const description = "معرفی خودرو چاره؛ سامانه هماهنگی امداد خودرو آنلاین تهران و کرج با بیش از ۱۵ سال پیشینه اجرایی، شبکه حدود ۱۰۰ امدادگر و پاسخ‌گویی شبانه‌روزی.";

export const metadata: Metadata = seoMetadata({ title: "درباره ما | سامانه امداد خودرو آنلاین", description, path: "/about", keywords: ["درباره خودرو چاره", "امداد خودرو آنلاین", "سامانه امداد خودرو", "امداد خودرو تهران", "امداد خودرو کرج"] });

const facts = [
  ["بیش از ۱۵ سال", "پیشینه فعالیت تیم اجرایی در خدمات خودرو"],
  ["حدود ۱۰۰ امدادگر", "شبکه فعال برای هماهنگی خدمات"],
  ["۲۴ ساعت، ۷ روز هفته", "پاسخ‌گویی شبانه‌روزی بدون تعطیلی"],
] as const;

const principles = [
  ["هماهنگی شفاف", "نوع خدمت و عوامل مؤثر بر هزینه پیش از شروع کار بررسی و با مالک خودرو هماهنگ می‌شود."],
  ["انتخاب خدمت متناسب", "بر اساس نشانه خرابی، موقعیت و نوع خودرو، مکانیک سیار، باتری، یدک‌کش یا خودروبر مناسب بررسی می‌شود."],
  ["پاسخ‌گویی پس از خدمت", `مسیر پیگیری و رسیدگی به شکایات از طریق شماره ${businessFacts.complaintPhone} در دسترس است.`],
] as const;

export default function AboutPage() {
  return <SubpageShell>
    <StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, { name: "درباره خودرو چاره" }], "/about")} />
    <StructuredData data={webPageSchema({ type: "AboutPage", name: "درباره خودرو چاره", description, path: "/about", breadcrumb: true })} />
    <section className="relative overflow-hidden bg-ink text-white"><div className="site-container relative py-14 md:py-20" dir="rtl"><SeoBreadcrumbs items={[{ label: "صفحه اصلی", href: "/" }, { label: "درباره خودرو چاره" }]} /><span className="mt-6 inline-flex text-xs font-black text-orange-300">معرفی خودرو چاره</span><h1 className="mt-5 max-w-5xl text-3xl font-black leading-[1.55] md:text-5xl">خودرو چاره؛ سامانه هماهنگی امداد خودرو آنلاین تهران و کرج</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-slate-300">خودرو چاره با پشتوانه بیش از ۱۵ سال تجربه عملی تیم اجرایی ایجاد شده است تا راننده بتواند در زمان خرابی یا نیاز به خدمات خودرو، درخواست خود را آنلاین ثبت کند و با متخصص متناسب با موقعیت و نوع مشکل هماهنگ شود.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/#request" className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-6 text-sm font-black text-white shadow-orange">ثبت درخواست آنلاین</Link><Link href="/contact" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-6 text-sm font-black">اطلاعات تماس و آدرس</Link></div></div></section>
    <section className="site-container mt-8 grid gap-4 md:grid-cols-3" dir="rtl">{facts.map(([value, label]) => <article key={value} className="rounded-2xl bg-white p-6 shadow-card"><strong className="text-xl font-black text-brand-orange">{value}</strong><p className="mt-3 text-sm leading-7 text-slate-500">{label}</p></article>)}</section>
    <section className="site-container mt-8 grid items-center gap-7 rounded-2xl bg-white p-6 shadow-card lg:grid-cols-2 md:p-9" dir="ltr"><div className="relative min-h-72 overflow-hidden rounded-2xl"><Image src="/images/facts/experienced-mechanic.webp" alt="تجربه تیم اجرایی خودرو چاره در خدمات خودرو" fill sizes="(min-width:1024px) 50vw,100vw" className="object-cover" /></div><article dir="rtl"><p className="text-xs font-black text-brand-orange">ما چه کاری انجام می‌دهیم؟</p><h2 className="mt-3 text-2xl font-black">از ثبت درخواست تا هماهنگی متخصص مناسب</h2><p className="mt-4 text-sm leading-8 text-slate-600">خودرو چاره یک مسیر آنلاین برای ثبت نیاز راننده و هماهنگی خدمات خودرو فراهم می‌کند. پس از دریافت مدل خودرو، موقعیت و شرح مشکل، امکان ارائه خدمت بررسی می‌شود. بسته به شرایط، امداد در محل یا حمل ایمن خودرو پیشنهاد می‌شود.</p><p className="mt-3 text-sm leading-8 text-slate-600">هدف ما جایگزین‌کردن تشخیص فنی با وعده‌های عمومی نیست؛ اطلاعات دقیق‌تر باعث می‌شود متخصص و تجهیزات مناسب‌تری انتخاب شود و راننده پیش از شروع کار تصویر روشن‌تری از خدمت داشته باشد.</p></article></section>
    <section className="site-container mt-8" dir="rtl"><h2 className="text-2xl font-black">خدمات خودرو چاره</h2><p className="mt-3 max-w-3xl text-sm leading-8 text-slate-600">شبکه خودرو چاره برای نیازهای متنوع رانندگان، از امداد خودرو آنلاین و تعمیرات قابل انجام در محل تا حمل خودرو و خدمات نگهداری هماهنگ می‌شود.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{businessFacts.services.map((service) => <div key={service} className="flex items-center gap-3 rounded-xl bg-white p-4 text-sm font-bold shadow-card"><Icon name="check" size={17} className="text-emerald-600" />{service}</div>)}</div><div className="mt-6 flex flex-wrap gap-3"><Link href="/services" className="inline-flex min-h-11 items-center rounded-lg bg-brand-orange px-5 text-sm font-black text-white">جزئیات همه خدمات</Link><Link href="/تهران" className="inline-flex min-h-11 items-center rounded-lg border border-slate-200 bg-white px-5 text-sm font-black">امداد خودرو تهران</Link><Link href="/کرج" className="inline-flex min-h-11 items-center rounded-lg border border-slate-200 bg-white px-5 text-sm font-black">امداد خودرو کرج</Link></div></section>
    <section className="site-container mt-8 grid gap-5 md:grid-cols-3" dir="rtl">{principles.map(([title, body]) => <article key={title} className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-lg font-black">{title}</h2><p className="mt-3 text-sm leading-8 text-slate-600">{body}</p></article>)}</section>
    <section className="site-container mt-8 grid gap-5 md:grid-cols-3" dir="rtl"><article className="overflow-hidden rounded-2xl bg-white shadow-card"><div className="relative h-40"><Image src="/images/facts/active-network.webp" alt="شبکه امداد خودرو در تهران و کرج" fill sizes="(min-width:768px) 33vw,100vw" className="object-cover" /></div><div className="p-6"><h2 className="font-black">پوشش تهران و کرج</h2><p className="mt-3 text-sm leading-7 text-slate-500">خدمات در مناطق ۲۲گانه تهران، کرج و محدوده‌های اعلام‌شده هماهنگ می‌شود.</p><Link href="/coverage" className="mt-3 inline-flex text-xs font-black text-brand-orange">مشاهده مناطق تحت پوشش ←</Link></div></article><article className="overflow-hidden rounded-2xl bg-white shadow-card"><div className="relative h-40"><Image src="/images/facts/fast-dispatch.webp" alt="هماهنگی اعزام امدادگر خودرو چاره" fill sizes="(min-width:768px) 33vw,100vw" className="object-cover" /></div><div className="p-6"><h2 className="font-black">اعزام معمولاً کمتر از ۳۰ دقیقه</h2><p className="mt-3 text-sm leading-7 text-slate-500">زمان دقیق با توجه به ترافیک، موقعیت، نوع خدمت و نزدیک‌ترین امدادگر آماده اعلام می‌شود.</p></div></article><article className="overflow-hidden rounded-2xl bg-white shadow-card"><div className="relative h-40"><Image src="/images/facts/support-24h.webp" alt="پشتیبانی شبانه‌روزی خودرو چاره" fill sizes="(min-width:768px) 33vw,100vw" className="object-cover" /></div><div className="p-6"><h2 className="font-black">هویت و راه ارتباطی روشن</h2><p className="mt-3 text-sm leading-7 text-slate-500">آدرس، تلفن امداد، ایمیل و مسیر رسیدگی به شکایت در صفحه تماس منتشر شده است.</p><Link href="/contact" className="mt-3 inline-flex text-xs font-black text-brand-orange">تماس با خودرو چاره ←</Link></div></article></section>
    <section className="site-container mt-8 rounded-2xl bg-ink p-7 text-white shadow-card md:p-9" dir="rtl"><h2 className="text-2xl font-black">اطلاعات رسمی خودرو چاره</h2><div className="mt-5 grid gap-4 text-sm leading-8 text-slate-300 md:grid-cols-2"><p><strong className="text-white">نام برند:</strong> خودرو چاره</p><p><strong className="text-white">حوزه فعالیت:</strong> هماهنگی خدمات و امداد خودرو آنلاین</p><p><strong className="text-white">محدوده اصلی:</strong> تهران و کرج</p><address className="not-italic"><strong className="text-white">آدرس:</strong> {businessFacts.address}</address><p><strong className="text-white">تلفن امداد:</strong> <a href={`tel:${businessFacts.emergencyPhone}`} dir="ltr">{businessFacts.emergencyPhone}</a></p><p><strong className="text-white">ایمیل:</strong> <a href={`mailto:${businessFacts.email}`}>{businessFacts.email}</a></p></div></section>
  </SubpageShell>;
}
