import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/home/home-ui";
import { SubpageShell } from "@/components/site/subpage-shell";
import { StructuredData } from "@/components/seo/structured-data";
import { breadcrumbSchema } from "@/seo/schemas";
import { seoMetadata } from "@/seo/metadata";

export const metadata: Metadata = seoMetadata({ title: "درباره خودرو چاره", description: "خودرو چاره بستری برای هماهنگی امداد خودرو و خدمات خودرو در محل با تمرکز فعلی بر تهران و کرج است.", path: "/about" });

export default function AboutPage() { return <SubpageShell><StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, { name: "درباره خودرو چاره" }])} /><section className="relative overflow-hidden bg-ink text-white"><div className="site-container relative py-14 md:py-20"><span className="text-xs font-black text-orange-300">درباره خودرو چاره</span><h1 className="mt-5 text-3xl font-black md:text-5xl">مسیر ساده‌تر برای دریافت کمک خودرو</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-slate-300">خودرو چاره برای کوتاه‌کردن مسیر بین راننده، مشکل خودرو و متخصص مناسب طراحی شده است؛ با تمرکز عملیاتی فعلی روی تهران و کرج.</p></div></section><section className="site-container mt-8 grid gap-5 md:grid-cols-3" dir="rtl"><article className="rounded-2xl bg-white p-6 shadow-card"><Icon name="location" size={26} className="text-brand-orange" /><h2 className="mt-4 font-black">انتخاب بر اساس موقعیت</h2><p className="mt-3 text-sm leading-7 text-slate-500">موقعیت، نوع خودرو و شرح مشکل، پایه هماهنگی خدمت هستند.</p></article><article className="rounded-2xl bg-white p-6 shadow-card"><Icon name="shield" size={26} className="text-brand-orange" /><h2 className="mt-4 font-black">اولویت با ایمنی</h2><p className="mt-3 text-sm leading-7 text-slate-500">در شرایط خطرناک، تماس با مراجع اضطراری رسمی مقدم بر ثبت درخواست است.</p></article><article className="rounded-2xl bg-white p-6 shadow-card"><Icon name="tag" size={26} className="text-brand-orange" /><h2 className="mt-4 font-black">هماهنگی شفاف</h2><p className="mt-3 text-sm leading-7 text-slate-500">مبنای هزینه و دامنه خدمت باید پیش از شروع برای کاربر روشن باشد.</p></article></section><section className="site-container mt-8 rounded-2xl bg-white p-7 shadow-card" dir="rtl"><h2 className="text-2xl font-black">خدمات خودرو چاره</h2><p className="mt-3 text-sm leading-8 text-slate-600">از امداد خودرو و باتری تا پنچرگیری، مکانیک سیار، یدک‌کش، خودروبر و کارواش سیار، خدمات در صفحات جداگانه توضیح داده شده‌اند تا کاربر قبل از ثبت درخواست مسیر مناسب را انتخاب کند.</p><Link href="/services" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-brand-orange px-5 text-sm font-black text-white">مشاهده همه خدمات</Link></section></SubpageShell>; }
