import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { businessFacts } from "@/content/business";
import { coverageUpdatedAt } from "@/content/coverage";
import { breadcrumbSchema, faqSchema, serviceSchema, webPageSchema } from "@/seo/schemas";
import { StructuredData } from "./structured-data";
import { SeoBreadcrumbs } from "./seo-breadcrumbs";

export type ContentLink = { title: string; href: string; description?: string };
export type Question = { question: string; answer: string };
export function LandingHeader({ title, intro, eyebrow = "خودرو چاره · راهنمای انتخاب و هماهنگی خدمت", image = "/images/support-technician-night.webp", crumbs = [] }: { title: string; intro: string; eyebrow?: string; image?: string; crumbs?: { label: string; href?: string }[] }) {
  return <section className="relative overflow-hidden bg-ink text-white"><div className="site-container grid items-center gap-8 py-12 lg:grid-cols-[1.15fr_.85fr] lg:py-16" dir="rtl"><div><SeoBreadcrumbs items={[{ label: "صفحه اصلی", href: "/" }, ...crumbs]} /><p className="mt-6 text-xs font-bold text-orange-300">{eyebrow}</p><h1 className="mt-4 text-3xl font-black leading-[1.65] md:text-4xl">{title}</h1><p className="mt-5 max-w-3xl text-base leading-9 text-slate-200">{intro}</p><div className="mt-6 flex flex-wrap gap-3"><a href={`tel:${businessFacts.emergencyPhone}`} className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-5 text-sm font-black">تماس برای امداد: <bdi className="mr-2">{businessFacts.emergencyPhone}</bdi></a><Link href="/امداد-خودرو-آنلاین#request" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-5 text-sm font-bold">آماده‌سازی درخواست آنلاین</Link></div></div><div className="relative min-h-64 overflow-hidden rounded-2xl border border-white/15 lg:min-h-96"><Image src={image} alt={`تصویر معرفی ${title}`} fill priority sizes="(min-width:1024px) 40vw,100vw" className="object-cover" /><span className="absolute bottom-3 right-3 rounded-md bg-black/60 px-2 py-1 text-[10px] text-white">تصویر معرفی خدمت؛ نه موقعیت زندهٔ امدادگر</span></div></div></section>;
}
export function LandingSchemas({ path, title, description, area, areaType, crumbs = [], collection = false }: { path: string; title: string; description: string; area?: string; areaType?: "City" | "AdministrativeArea" | "Place"; crumbs?: { name: string; path?: string }[]; collection?: boolean }) {
  return <><StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, ...crumbs, { name: title }], path)} /><StructuredData data={webPageSchema({ type: collection ? "CollectionPage" : "WebPage", path, name: title, description, breadcrumb: true })} />{area && <StructuredData data={serviceSchema({ name: title, description, path, area, areaType })} />}</>;
}
export function Section({ id, title, children }: { id?: string; title: string; children: ReactNode }) {
  return <section id={id} className="site-container mt-8 scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-8" dir="rtl"><h2 className="text-xl font-black leading-9 text-ink md:text-2xl">{title}</h2><div className="mt-4 space-y-4 text-sm leading-8 text-slate-600">{children}</div></section>;
}
export function AnswerBox({ children }: { children: ReactNode }) {
  return <section className="site-container mt-8 rounded-2xl border border-orange-200 bg-orange-50 p-6 md:p-8" aria-label="پاسخ کوتاه" dir="rtl"><h2 className="text-lg font-black text-ink">پاسخ کوتاه</h2><div className="mt-3 text-sm leading-8 text-slate-700">{children}</div><p className="mt-4 text-xs leading-6 text-slate-500">به‌روزرسانی محتوای صفحه: <time dateTime={coverageUpdatedAt}>۱۴ شهریور ۱۴۰۵</time> · تهیه‌شده توسط خودرو چاره · <Link href="/editorial-policy" className="underline underline-offset-4">روش تدوین و اصلاح اطلاعات</Link></p></section>;
}
export function LinkGrid({ links, label = "صفحات مرتبط" }: { links: readonly ContentLink[]; label?: string }) {
  return <nav aria-label={label} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{links.map((item) => <Link key={item.href} href={item.href} className="block rounded-xl border border-slate-200 bg-slate-50 p-4 transition hover:border-orange-300 hover:bg-orange-50"><span className="font-black text-ink">{item.title} <span aria-hidden="true">←</span></span>{item.description && <p className="mt-2 text-xs leading-7 text-slate-600">{item.description}</p>}</Link>)}</nav>;
}
export function Questions({ items, title = "پرسش‌های متداول" }: { items: readonly Question[]; title?: string }) {
  return <><StructuredData data={faqSchema(items)} /><Section title={title}><div className="divide-y divide-slate-200">{items.map((item) => <details key={item.question} className="py-4"><summary className="cursor-pointer font-bold text-ink">{item.question}</summary><p className="mt-3 leading-8">{item.answer}</p></details>)}</div></Section></>;
}
export function PriceFactors({ area }: { area: string }) {
  return <Section title={`هزینه و زمان اعزام در ${area} چگونه مشخص می‌شود؟`}><p>نرخ یا زمان یکسان برای همه درخواست‌ها اعلام نمی‌کنیم. پیش از شروع، هزینه اعزام، دامنه کار، قطعات احتمالی و در حمل خودرو، مسیر و بارگیری با مالک هماهنگ می‌شود. برای تصمیم‌گیری، این موارد را جدا بپرسید:</p><div className="overflow-x-auto"><table className="w-full min-w-[480px] text-right text-sm"><caption className="sr-only">اجزای برآورد هزینه خدمات خودرو</caption><thead className="bg-slate-100 text-ink"><tr><th scope="col" className="p-3">عامل</th><th scope="col" className="p-3">اطلاعات لازم برای استعلام</th></tr></thead><tbody>{[["نوع خدمت و خودرو", "عیب‌یابی، تعمیر، باتری یا حمل؛ مدل، گیربکس و وزن"], ["مسیر و دسترسی", "مبدأ و مقصد، جهت حرکت، ورودی پارکینگ یا راه فرعی"], ["تجهیزات و کار اضافه", "چرخ قفل‌شده، رمپ دشوار، انتظار، قطعه و عوارض"], ["زمان اعزام", "ظرفیت متخصص، ترافیک، شرایط راه و امکان توقف ایمن"]].map(([factor, value]) => <tr key={factor} className="border-b border-slate-100"><th scope="row" className="p-3 font-bold">{factor}</th><td className="p-3">{value}</td></tr>)}</tbody></table></div><Link href="/pricing" className="inline-flex min-h-11 items-center font-black text-brand-orange">راهنمای قیمت و محاسبه با تعرفهٔ اعلام‌شده ←</Link></Section>;
}
export function SafetyNote() {
  return <Section title="اول ایمنی؛ امداد خودرو جای خدمات نجات نیست"><p>در مصدومیت، آتش‌سوزی، نشت سوخت، سیلاب یا توقف بسیار خطرناک، ابتدا با پلیس و خدمات اضطراری مربوط تماس بگیرید. برای قراردادن علامت یا تعمیر، خودتان را وارد مسیر عبور خودروها نکنید. از بازکردن مدار خنک‌کننده داغ و دستکاری سامانه ولتاژ بالای خودروهای برقی و هیبریدی خودداری کنید.</p><p>این صفحات وضعیت زنده ترافیک یا بازبودن جاده را نمایش نمی‌دهند. برای محدودیت تردد و وضعیت راه به <a href="https://141.ir/" rel="noopener noreferrer" target="_blank" className="font-bold text-brand-orange underline">سامانه رسمی ۱۴۱ سازمان راهداری</a> مراجعه کنید؛ راهنمای فنی نهایی، دفترچه همان مدل و نظر متخصص پس از بازدید است.</p></Section>;
}
export function FinalContact({ title = "برای هماهنگی خدمت آماده‌اید؟" }: { title?: string }) {
  return <section className="site-container mt-8 rounded-2xl bg-ink p-7 text-white" dir="rtl"><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 text-sm leading-8 text-slate-300">موقعیت دقیق، مدل خودرو و نشانه خرابی را آماده کنید. ثبت نهایی اعزام، زمان و مبلغ پس از تأیید اپراتور انجام می‌شود؛ تماس در وضعیت فوری سریع‌ترین مسیر هماهنگی است.</p><div className="mt-5 flex flex-wrap gap-3"><a href={`tel:${businessFacts.emergencyPhone}`} className="rounded-lg bg-brand-orange px-5 py-3 font-black" dir="ltr">{businessFacts.emergencyPhone}</a><Link href="/امداد-خودرو-آنلاین#request" className="rounded-lg border border-white/30 px-5 py-3 text-sm font-bold">تکمیل اطلاعات درخواست</Link><a href={businessFacts.baleUrl} target="_blank" rel="me noopener noreferrer" className="rounded-lg border border-white/30 px-5 py-3 text-sm font-bold">کانال رسمی بله</a></div><p className="mt-3 text-xs leading-7 text-slate-400">کانال بله برای اطلاع‌رسانی است؛ عضویت در کانال به معنی ثبت سفارش امداد نیست.</p></section>;
}
