import { SubpageShell } from "@/components/site/subpage-shell";
import { neighborhoods } from "@/content/neighborhoods";
import { seoRegions, type SeoLocation, type SeoRegion } from "@/seo/locations";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, PriceFactors, Questions, SafetyNote, Section } from "./landing-ui";
import { cityServiceLinks } from "./location-landings";
export { CityLanding as ExpandedCityLanding } from "./location-landings";
export function ExpandedRegionLanding({ location, region }: { location: SeoLocation; region: SeoRegion }) {
  const path = `/${location.slug}/${region.slug}`; const title = `امداد خودرو ${region.name}`; const areas = neighborhoods.filter((item) => item.citySlug === location.slug && item.regionSlug === region.slug);
  return <SubpageShell><LandingSchemas path={path} title={title} description={region.description} area={region.name} areaType="Place" crumbs={[{ name: location.name, path: `/${location.slug}` }]} /><LandingHeader title={title} intro={region.description} image={region.image} crumbs={[{ label: location.name, href: `/${location.slug}` }, { label: region.name }]} /><AnswerBox><p>{region.serviceNote} برای هماهنگی، مدل خودرو و لوکیشن دقیق را با 09123022064 اعلام کنید. اعزام و مبلغ پس از بررسی ظرفیت و دسترسی مشخص می‌شود.</p></AnswerBox><Section title={`محدوده‌ها و راه‌های ${region.name}`}><p>{region.neighborhoods.join("؛ ")}</p><p>{region.routes.join("؛ ")}</p><p>{region.serviceNote}</p></Section>{areas.length > 0 && <Section title="راهنمای اختصاصی محله‌ها"><LinkGrid links={areas.map((item) => ({ title: `امداد خودرو ${item.name}`, href: `/${item.citySlug}/${item.slug}`, description: item.landmarks.join("، ") }))} /></Section>}<Section title="خدمات در محل و حمل خودرو"><LinkGrid links={cityServiceLinks(location)} /></Section><PriceFactors area={region.name} /><Questions items={region.faqs} /><Section title="سایر مناطق تهران"><LinkGrid links={Object.values(seoRegions).filter((item) => item.slug !== region.slug).map((item) => ({ title: `امداد خودرو ${item.name}`, href: `/${item.citySlug}/${item.slug}` }))} /></Section><SafetyNote /><FinalContact /></SubpageShell>;
}
