import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/home/home-ui";
import { SubpageShell } from "@/components/site/subpage-shell";
import { getService } from "@/content/services";
import { breadcrumbSchema, faqSchema, serviceSchema } from "@/seo/schemas";
import { cityServicePath, persianServiceRoutes } from "@/seo/internal-links";
import { seoRegions, type SeoLocation, type SeoRegion } from "@/seo/locations";
import { SeoBreadcrumbs } from "./seo-breadcrumbs";
import { StructuredData } from "./structured-data";

function servicesForCity(citySlug: string) {
  return persianServiceRoutes.map((route) => ({ ...route, href: cityServicePath(citySlug, route.slug), service: getService(route.serviceSlug) })).filter((item) => item.service);
}

const tehranGuides = [
  { title: "مناطق تحت پوشش امداد خودرو تهران و کرج", href: "/blog/car-assistance-coverage-tehran-karaj" },
  { title: "وقتی خودرو در بزرگراه خاموش می‌شود چه کنیم؟", href: "/blog/what-to-do-when-car-stops-on-highway" },
  { title: "هزینه حمل خودرو با یدک‌کش", href: "/blog/car-tow-truck-price-guide" },
  { title: "چک‌لیست انتخاب مکانیک سیار", href: "/blog/mobile-mechanic-checklist" },
] as const;

export function ExpandedCityLanding({ location }: { location: SeoLocation }) {
  const links = servicesForCity(location.slug);
  const regions = Object.values(seoRegions).filter((region) => region.citySlug === location.slug);
  const faqs = [
    { question: `امداد خودرو ${location.name} شبانه‌روزی است؟`, answer: "پاسخ‌گویی خودرو چاره به‌صورت ۲۴ ساعته و در تمام روزهای هفته انجام می‌شود. امکان و زمان اعزام پس از بررسی موقعیت و نوع خدمت اعلام می‌شود." },
    { question: `زمان رسیدن امدادگر در ${location.name} چقدر است؟`, answer: "اعزام معمولاً کمتر از ۳۰ دقیقه انجام می‌شود؛ ترافیک، ساعت درخواست، محله، نوع خودرو و فاصله نزدیک‌ترین امدادگر روی زمان دقیق اثر دارند." },
    { question: `قیمت امداد خودرو ${location.name} چگونه محاسبه می‌شود؟`, answer: "نوع خدمت، مدل خودرو، تجهیزات لازم، شرایط محل و برای حمل خودرو، مبدأ و مقصد روی هزینه اثر دارند. مبنای هزینه پیش از شروع خدمت هماهنگ می‌شود." },
    { question: "چه زمانی یدک‌کش یا خودروبر لازم است؟", answer: "اگر خودرو امکان حرکت ایمن ندارد، چرخ یا فرمان آسیب دیده، گیربکس محدودیت دارد یا تعمیر در محل ممکن نیست، نوع وسیله حمل متناسب با وضعیت واقعی خودرو بررسی می‌شود." },
  ];
  return <SubpageShell>
    <StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, { name: location.name }])} />
    <StructuredData data={serviceSchema({ name: `امداد خودرو ${location.name}`, description: location.description, path: `/${location.slug}`, area: location.name })} />
    <StructuredData data={faqSchema(faqs)} />
    <section className="relative overflow-hidden bg-ink text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(255,83,21,.2),transparent_25%),radial-gradient(circle_at_80%_35%,rgba(14,165,233,.2),transparent_30%)]" /><div className="site-container relative grid items-center gap-8 py-14 lg:grid-cols-[1.05fr_.95fr] lg:py-20" dir="ltr"><div className="relative min-h-72 overflow-hidden rounded-[1.8rem] border border-white/15 lg:min-h-[430px]"><Image src="/images/support-technician-night.webp" alt={`امدادگر شبانه‌روزی خودرو چاره در ${location.name}`} fill priority sizes="(min-width:1024px) 48vw,100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-ink/60 via-transparent to-transparent" /></div><div dir="rtl"><SeoBreadcrumbs items={[{ label: "صفحه اصلی", href: "/" }, { label: location.name }]} /><span className="mt-6 inline-flex rounded-full border border-orange-300/25 bg-orange-300/10 px-4 py-2 text-xs font-black text-orange-200">پاسخ‌گویی ۲۴ ساعته، ۷ روز هفته</span><h1 className="mt-5 text-3xl font-black leading-[1.55] md:text-5xl">امداد خودرو {location.name} شبانه‌روزی و آنلاین</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-slate-300">{location.description} برای انتخاب خدمت مناسب، مدل خودرو، نشانه خرابی، امکان حرکت و لوکیشن دقیق را ثبت کنید.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/#request" className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-6 text-sm font-black text-white shadow-orange">ثبت درخواست امداد آنلاین</Link><a href="tel:09123022064" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-6 text-sm font-black" dir="ltr">09123022064</a></div></div></div></section>
    <section className="site-container mt-9" dir="rtl"><h2 className="text-2xl font-black">خدمات امداد خودرو در {location.name}</h2><p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600">از روشن‌نشدن خودرو و پنچری تا خرابی فنی یا نیاز به حمل، هر خدمت صفحه اختصاصی با جزئیات، موارد استفاده، مراحل درخواست، عوامل قیمت و سؤالات متداول دارد.</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{links.map((item) => <Link key={item.slug} href={item.href} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card transition hover:-translate-y-1"><div className="relative h-36"><Image src={item.service!.image} alt={`${item.title} در ${location.name}`} fill sizes="(min-width:1280px) 25vw,(min-width:768px) 50vw,100vw" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-4"><h3 className="font-black">{item.title} {location.name}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{item.service!.summary}</p><span className="mt-3 inline-flex text-xs font-black text-brand-orange">جزئیات و ثبت درخواست ←</span></div></Link>)}</div></section>
    {regions.length ? <section className="site-container mt-10" dir="rtl"><h2 className="text-2xl font-black">امداد خودرو در مناطق ۲۲گانه تهران</h2><p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600">برای جلوگیری از صفحات محله‌ای تکراری، پوشش تهران در پنج Hub عملیاتی دسته‌بندی شده است. هر صفحه محله‌ها، مناطق شهرداری، مسیرهای اصلی و شرایط واقعی هماهنگی را توضیح می‌دهد.</p><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{regions.map((region) => <Link key={region.slug} href={`/${region.citySlug}/${region.slug}`} className="group overflow-hidden rounded-2xl bg-white shadow-card transition hover:-translate-y-1"><div className="relative h-44"><Image src={region.image} alt={`امداد خودرو ${region.name}`} fill sizes="(min-width:1280px) 33vw,(min-width:768px) 50vw,100vw" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><h3 className="text-lg font-black">امداد خودرو {region.name}</h3><p className="mt-2 text-xs leading-7 text-slate-500">{region.districts.join("، ")}؛ {region.neighborhoods[0]}</p><span className="mt-3 inline-flex text-xs font-black text-brand-orange">مشاهده مناطق و خدمات ←</span></div></Link>)}</div></section> : null}
    {location.slug === "تهران" ? <section className="site-container mt-10 grid gap-6 lg:grid-cols-[1.15fr_.85fr]" dir="ltr"><article className="rounded-2xl bg-white p-6 shadow-card md:p-8" dir="rtl"><h2 className="text-2xl font-black">پوشش مناطق ۱ تا ۲۲ تهران</h2><p className="mt-4 text-sm leading-8 text-slate-600">شبکه خودرو چاره درخواست را در همه مناطق تهران بررسی می‌کند. قرارگرفتن نام منطقه در فهرست به معنی زمان ثابت نیست؛ ظرفیت لحظه‌ای، ترافیک و دسترسی محل پیش از اعزام کنترل می‌شود.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{regions.map((region) => <div key={region.slug} className="rounded-xl bg-slate-50 p-4"><h3 className="font-black">{region.name}</h3><p className="mt-2 text-xs leading-7 text-slate-500">{region.districts.join("، ")}</p><p className="mt-2 text-xs leading-7 text-slate-500">{region.neighborhoods.join("؛ ")}</p></div>)}</div></article><aside className="rounded-2xl bg-ink p-6 text-white md:p-8" dir="rtl"><h2 className="text-2xl font-black">امداد در بزرگراه‌های تهران</h2><p className="mt-4 text-sm leading-8 text-slate-300">در همت، حکیم، چمران، مدرس، امام علی، آزادگان، بابایی، باقری، ستاری و مسیر تهران–کرج، جهت حرکت و نزدیک‌ترین خروجی را همراه لوکیشن ارسال کنید.</p><ul className="mt-5 grid gap-3 text-xs leading-7 text-slate-300"><li className="rounded-xl bg-white/5 p-4">فلاشر را روشن و در صورت امکان در محل امن توقف کنید.</li><li className="rounded-xl bg-white/5 p-4">از ایستادن کنار جریان عبور یا تعویض چرخ در شانه باریک خودداری کنید.</li><li className="rounded-xl bg-white/5 p-4">در آتش‌سوزی، نشت سوخت یا مصدومیت ابتدا با خدمات اضطراری تماس بگیرید.</li></ul><Link href="/blog/what-to-do-when-car-stops-on-highway" className="mt-5 inline-flex text-sm font-black text-orange-300">راهنمای توقف در بزرگراه ←</Link></aside></section> : null}
    <section className="site-container mt-10 grid gap-5 lg:grid-cols-3" dir="rtl"><article className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">مراحل درخواست آنلاین</h2><ol className="mt-5 space-y-4">{["انتخاب نوع خدمت و ثبت مدل خودرو", "ارسال موقعیت و شرح کوتاه مشکل", "بررسی امکان خدمت، زمان و عوامل هزینه", "هماهنگی اعزام و پیگیری درخواست"].map((step, index) => <li key={step} className="flex gap-3 text-sm leading-7 text-slate-600"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-orange-50 font-black text-brand-orange">{(index + 1).toLocaleString("fa-IR")}</span>{step}</li>)}</ol></article><article className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">زمان اعزام و دسترسی</h2><p className="mt-4 text-sm leading-8 text-slate-600">اعزام معمولاً کمتر از ۳۰ دقیقه انجام می‌شود. زمان قطعی نیست و به ترافیک، ساعت درخواست، محل توقف، طرح‌های شهری و فاصله نزدیک‌ترین امدادگر بستگی دارد.</p><p className="mt-3 text-sm leading-8 text-slate-600">برای پارکینگ، رمپ، کوچه باریک یا مسیر بزرگراهی، محدودیت دسترسی را از ابتدا اعلام کنید.</p></article><article className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">عوامل مؤثر بر قیمت</h2><p className="mt-4 text-sm leading-8 text-slate-600">نوع خودرو و خدمت، قطعه یا تجهیزات، شرایط محل و ساعت درخواست بر هزینه اثر دارند. در حمل خودرو، مبدأ، مقصد، وضعیت چرخ و فرمان و روش بارگیری نیز محاسبه می‌شوند.</p><Link href="/pricing" className="mt-4 inline-flex text-sm font-black text-brand-orange">راهنمای قیمت خدمات ←</Link></article></section>
    {location.slug === "تهران" ? <section className="site-container mt-10 rounded-2xl bg-white p-6 shadow-card md:p-8" dir="rtl"><h2 className="text-2xl font-black">راهنماهای مرتبط با امداد خودرو تهران</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{tehranGuides.map((guide) => <Link key={guide.href} href={guide.href} className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-black transition hover:border-orange-200 hover:text-brand-orange">{guide.title} ←</Link>)}</div></section> : null}
    <section className="site-container mt-10 rounded-2xl bg-white p-6 shadow-card md:p-8" dir="rtl"><h2 className="text-2xl font-black">سؤالات متداول امداد خودرو {location.name}</h2><div className="mt-5 divide-y divide-slate-100">{faqs.map((faq) => <details key={faq.question} className="py-5"><summary className="cursor-pointer font-black">{faq.question}</summary><p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600">{faq.answer}</p></details>)}</div></section>
    <section className="site-container mt-10 rounded-2xl bg-ink p-7 text-center text-white shadow-card" dir="rtl"><h2 className="text-2xl font-black">برای خودرو در {location.name} کمک می‌خواهید؟</h2><p className="mt-3 text-sm leading-8 text-slate-300">موقعیت، مدل خودرو و نشانه مشکل را ثبت کنید یا برای هماهنگی فوری با پشتیبانی شبانه‌روزی تماس بگیرید.</p><div className="mt-5 flex flex-wrap justify-center gap-3"><Link href="/#request" className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-6 text-sm font-black">ثبت درخواست آنلاین</Link><a href="tel:09123022064" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-6 text-sm font-black" dir="ltr">09123022064</a></div></section>
  </SubpageShell>;
}

export function ExpandedRegionLanding({ location, region }: { location: SeoLocation; region: SeoRegion }) {
  const links = servicesForCity(location.slug).slice(0, 7);
  const otherRegions = Object.values(seoRegions).filter((item) => item.slug !== region.slug);
  const path = `/${region.citySlug}/${region.slug}`;
  return <SubpageShell>
    <StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, { name: "تهران", path: "/تهران" }, { name: region.name }])} />
    <StructuredData data={serviceSchema({ name: `امداد خودرو ${region.name}`, description: region.description, path, area: "تهران" })} />
    <StructuredData data={faqSchema(region.faqs)} />
    <section className="relative overflow-hidden bg-ink text-white"><div className="site-container grid items-center gap-8 py-14 lg:grid-cols-[.9fr_1.1fr] lg:py-20" dir="ltr"><div className="relative min-h-72 overflow-hidden rounded-[1.8rem] border border-white/15 lg:min-h-[430px]"><Image src={region.image} alt={`خدمات امداد خودرو ${region.name}`} fill priority sizes="(min-width:1024px) 45vw,100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-ink/55 via-transparent to-transparent" /></div><div dir="rtl"><SeoBreadcrumbs items={[{ label: "صفحه اصلی", href: "/" }, { label: "امداد خودرو تهران", href: "/تهران" }, { label: region.name }]} /><span className="mt-6 inline-flex text-xs font-black text-orange-300">Hub منطقه‌ای خودرو چاره</span><h1 className="mt-4 text-3xl font-black leading-[1.55] md:text-5xl">امداد خودرو {region.name} شبانه‌روزی</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-slate-300">{region.description} درخواست بر اساس لوکیشن، شرایط خودرو و ظرفیت همان زمان بررسی می‌شود.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/#request" className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-6 text-sm font-black text-white shadow-orange">درخواست امداد آنلاین</Link><a href="tel:09123022064" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-6 text-sm font-black" dir="ltr">09123022064</a></div></div></div></section>
    <section className="site-container mt-8 grid gap-4 md:grid-cols-3" dir="rtl"><article className="rounded-2xl bg-white p-5 shadow-card"><strong className="text-lg font-black text-brand-orange">{region.districts.join("، ")}</strong><p className="mt-2 text-xs leading-7 text-slate-500">مناطق شهرداری این Hub</p></article><article className="rounded-2xl bg-white p-5 shadow-card"><strong className="text-lg font-black text-brand-orange">۲۴ ساعت، ۷ روز هفته</strong><p className="mt-2 text-xs leading-7 text-slate-500">پاسخ‌گویی و بررسی درخواست</p></article><article className="rounded-2xl bg-white p-5 shadow-card"><strong className="text-lg font-black text-brand-orange">اعزام معمولاً زیر ۳۰ دقیقه</strong><p className="mt-2 text-xs leading-7 text-slate-500">متناسب با ترافیک و موقعیت</p></article></section>
    <section className="site-container mt-9 grid gap-6 lg:grid-cols-2" dir="rtl"><article className="rounded-2xl bg-white p-6 shadow-card md:p-8"><h2 className="text-2xl font-black">محله‌های تحت پوشش {region.name}</h2><p className="mt-3 text-sm leading-8 text-slate-600">این فهرست برای توضیح محدوده عملیاتی است. امکان اعزام در هر درخواست با لوکیشن دقیق و ظرفیت همان زمان کنترل می‌شود.</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{region.neighborhoods.map((item) => <li key={item} className="rounded-xl bg-slate-50 p-4 text-sm font-bold leading-7 text-slate-700">{item}</li>)}</ul></article><article className="rounded-2xl bg-white p-6 shadow-card md:p-8"><h2 className="text-2xl font-black">مسیرها و دسترسی‌های اصلی</h2><p className="mt-3 text-sm leading-8 text-slate-600">در بزرگراه و مسیرهای چندجهته، نام مسیر به‌تنهایی کافی نیست. جهت حرکت، خروجی نزدیک و موقعیت امن توقف را اعلام کنید.</p><ul className="mt-5 grid gap-3">{region.routes.map((route) => <li key={route} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 text-sm font-bold"><Icon name="location" size={18} className="text-brand-orange" />{route}</li>)}</ul></article></section>
    <section className="site-container mt-9" dir="rtl"><h2 className="text-2xl font-black">خدمات خودرو چاره در {region.name}</h2><p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600">نوع خدمت پس از دریافت نشانه خرابی انتخاب می‌شود. اگر تعمیر در محل ایمن یا ممکن نباشد، حمل خودرو با وسیله متناسب بررسی خواهد شد.</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{links.map((item) => <Link key={item.slug} href={item.href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-card transition hover:-translate-y-1"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-50 text-brand-orange"><Icon name={item.service!.icon} size={21} /></span><h3 className="font-black">{item.title} تهران</h3></div><p className="mt-3 text-xs leading-7 text-slate-500">{item.service!.summary}</p><span className="mt-3 inline-flex text-xs font-black text-brand-orange">جزئیات خدمت ←</span></Link>)}</div></section>
    <section className="site-container mt-9 grid gap-6 lg:grid-cols-[1.1fr_.9fr]" dir="rtl"><article className="rounded-2xl bg-white p-6 shadow-card md:p-8"><h2 className="text-2xl font-black">شرایط واقعی هماهنگی در {region.name}</h2><p className="mt-4 text-sm leading-9 text-slate-600">{region.serviceNote}</p><p className="mt-3 text-sm leading-9 text-slate-600">زمان اعزام و مبلغ ثابت برای همه درخواست‌ها یکسان نیست. نوع خودرو، ساعت، ترافیک، تجهیزات و در حمل خودرو، مبدأ و مقصد بررسی می‌شوند. هر خدمت اضافه باید پیش از انجام با مالک خودرو هماهنگ شود.</p></article><aside className="rounded-2xl bg-ink p-6 text-white md:p-8"><h2 className="text-xl font-black">اطلاعات لازم هنگام درخواست</h2><ul className="mt-5 grid gap-3 text-sm leading-7 text-slate-300"><li className="rounded-xl bg-white/5 p-4">مدل، نوع گیربکس و وضعیت روشن‌شدن خودرو</li><li className="rounded-xl bg-white/5 p-4">لوکیشن، نام محله و مسیر دسترسی</li><li className="rounded-xl bg-white/5 p-4">شرح خرابی، چراغ هشدار یا آسیب چرخ</li><li className="rounded-xl bg-white/5 p-4">مقصد احتمالی در صورت نیاز به حمل</li></ul></aside></section>
    <section className="site-container mt-9 rounded-2xl bg-white p-6 shadow-card md:p-8" dir="rtl"><h2 className="text-2xl font-black">سؤالات متداول امداد خودرو {region.name}</h2><div className="mt-5 divide-y divide-slate-100">{region.faqs.map((faq) => <details key={faq.question} className="py-5"><summary className="cursor-pointer font-black">{faq.question}</summary><p className="mt-3 max-w-4xl text-sm leading-8 text-slate-600">{faq.answer}</p></details>)}</div></section>
    <section className="site-container mt-9 rounded-2xl border border-slate-200 bg-white p-6 shadow-card" dir="rtl"><h2 className="text-xl font-black">سایر مناطق امداد خودرو تهران</h2><nav className="mt-4 flex flex-wrap gap-3" aria-label="سایر مناطق تهران">{otherRegions.map((item) => <Link key={item.slug} href={`/${item.citySlug}/${item.slug}`} className="inline-flex min-h-11 items-center rounded-lg bg-slate-50 px-4 text-sm font-black transition hover:bg-orange-50 hover:text-brand-orange">امداد خودرو {item.name}</Link>)}</nav><Link href="/تهران" className="mt-5 inline-flex text-sm font-black text-brand-orange">بازگشت به صفحه امداد خودرو تهران ←</Link></section>
  </SubpageShell>;
}
