import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ContactForm } from "@/components/site/contact-form";
import { SeoBreadcrumbs } from "@/components/seo/seo-breadcrumbs";
import { StructuredData } from "@/components/seo/structured-data";
import { SubpageShell } from "@/components/site/subpage-shell";
import { businessFacts } from "@/content/business";
import { breadcrumbSchema, webPageSchema } from "@/seo/schemas";
import { seoMetadata } from "@/seo/metadata";

const description = "آدرس و راه‌های تماس با خودرو چاره؛ پشتیبانی شبانه‌روزی امداد خودرو آنلاین تهران و کرج، پیگیری خدمات، رسیدگی به شکایات و فرم تماس.";

export const metadata: Metadata = seoMetadata({ title: "تماس با خودرو چاره | آدرس و پشتیبانی شبانه‌روزی", description, path: "/contact", keywords: ["تماس با خودرو چاره", "شماره امداد خودرو", "پشتیبانی امداد خودرو", "آدرس خودرو چاره"] });

const contactCards = [
  { href: `tel:${businessFacts.emergencyPhone}`, image: "/images/facts/fast-dispatch.webp", alt: "پاسخ‌گویی تلفنی امداد خودرو چاره", title: "امداد و اعزام فوری", value: businessFacts.emergencyPhone, note: "پاسخ‌گویی ۲۴ ساعته، ۷ روز هفته" },
  { href: `tel:${businessFacts.complaintPhone}`, image: "/images/facts/support-24h.webp", alt: "پشتیبانی و رسیدگی به شکایات خودرو چاره", title: "پیگیری و شکایات", value: businessFacts.complaintPhone, note: "پیگیری کیفیت خدمت و ثبت بازخورد" },
  { href: `mailto:${businessFacts.email}`, image: "/images/facts/experienced-mechanic.webp", alt: "ارتباط ایمیلی با خودرو چاره", title: "ایمیل پشتیبانی", value: businessFacts.email, note: "پیشنهاد، همکاری و درخواست‌های غیرفوری" },
] as const;

export default function ContactPage() {
  return <SubpageShell>
    <StructuredData data={breadcrumbSchema([{ name: "صفحه اصلی", path: "/" }, { name: "تماس با ما" }])} />
    <StructuredData data={webPageSchema({ type: "ContactPage", name: "تماس با خودرو چاره", description, path: "/contact" })} />
    <section className="relative overflow-hidden bg-ink text-white"><div className="site-container relative py-14 md:py-20" dir="rtl"><SeoBreadcrumbs items={[{ label: "صفحه اصلی", href: "/" }, { label: "تماس با ما" }]} /><span className="mt-6 inline-flex text-xs font-black text-orange-300">پشتیبانی ۲۴ ساعته خودرو چاره</span><h1 className="mt-5 text-3xl font-black md:text-5xl">تماس با خودرو چاره</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-slate-300">برای ثبت درخواست امداد خودرو آنلاین، پیگیری خدمت، پیشنهاد همکاری یا ثبت بازخورد با ما در ارتباط باشید. برای وضعیت فوری، تماس تلفنی سریع‌ترین راه هماهنگی است.</p><div className="mt-7 flex flex-wrap gap-3"><a href={`tel:${businessFacts.emergencyPhone}`} className="inline-flex min-h-12 items-center rounded-lg bg-brand-orange px-6 text-sm font-black text-white shadow-orange">تماس فوری: {businessFacts.emergencyPhone}</a><Link href="/#request" className="inline-flex min-h-12 items-center rounded-lg border border-white/30 px-6 text-sm font-black">ثبت درخواست آنلاین</Link></div></div></section>
    <section className="site-container mt-8 grid gap-5 md:grid-cols-3" dir="rtl">{contactCards.map((item) => <a key={item.href} href={item.href} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-card transition hover:-translate-y-1"><div className="relative h-36"><Image src={item.image} alt={item.alt} fill sizes="(min-width:768px) 33vw,100vw" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><h2 className="font-black">{item.title}</h2><p className="mt-2 text-sm font-bold text-brand-orange" dir="ltr">{item.value}</p><p className="mt-2 text-xs leading-6 text-slate-500">{item.note}</p></div></a>)}</section>
    <section className="site-container mt-8 grid gap-6 lg:grid-cols-[.85fr_1.15fr]" dir="ltr"><aside className="overflow-hidden rounded-2xl bg-ink text-white shadow-card" dir="rtl"><div className="relative h-52"><Image src="/images/facts/active-network.webp" alt="دفتر و محدوده فعالیت خودرو چاره در تهران" fill sizes="(min-width:1024px) 42vw,100vw" className="object-cover opacity-75" /></div><div className="p-6"><h2 className="text-2xl font-black">آدرس خودرو چاره</h2><address className="mt-4 not-italic text-sm leading-8 text-slate-300">{businessFacts.address}</address><p className="mt-4 text-xs leading-7 text-slate-400">پیش از مراجعه حضوری، برای هماهنگی زمان و واحد مربوط با پشتیبانی تماس بگیرید. خدمات امدادی در محل خودرو ارائه و اعزام از طریق سامانه هماهنگ می‌شود.</p></div></aside><article className="rounded-2xl bg-white p-6 shadow-card md:p-8" dir="rtl"><p className="text-xs font-black text-brand-orange">پیام غیرفوری</p><h2 className="mt-3 text-2xl font-black">فرم تماس با ما</h2><p className="mb-6 mt-3 text-sm leading-8 text-slate-600">مشخصات و موضوع پیام را وارد کنید. با انتخاب دکمه ارسال، پیام در نرم‌افزار ایمیل شما آماده می‌شود و اطلاعات بدون تأیید شما ارسال نخواهد شد.</p><ContactForm /></article></section>
    <section className="site-container mt-8 grid gap-5 md:grid-cols-2" dir="rtl"><article className="rounded-2xl bg-white p-7 shadow-card"><h2 className="text-2xl font-black">هنگام درخواست امداد چه اطلاعاتی آماده کنیم؟</h2><ul className="mt-5 grid gap-3 text-sm leading-7 text-slate-600"><li className="rounded-xl bg-slate-50 p-4">مدل و نوع خودرو و امکان روشن‌شدن یا حرکت آن</li><li className="rounded-xl bg-slate-50 p-4">موقعیت دقیق، نام محله و نزدیک‌ترین خیابان یا بزرگراه</li><li className="rounded-xl bg-slate-50 p-4">شرح کوتاه نشانه خرابی و شماره تماس در دسترس</li></ul></article><article className="rounded-2xl bg-white p-7 shadow-card"><h2 className="text-2xl font-black">خدمات و محدوده فعالیت</h2><p className="mt-4 text-sm leading-8 text-slate-600">خودرو چاره خدمات امداد خودرو در محل، مکانیک و دیاگ سیار، باتری، پنچرگیری، یدک‌کش، خودروبر و کارواش سیار را در تهران و کرج هماهنگ می‌کند.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/services" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black">مشاهده خدمات</Link><Link href="/coverage" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black">مناطق تحت پوشش</Link><Link href="/about" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black">درباره خودرو چاره</Link></div></article></section>
  </SubpageShell>;
}
