import { allCities, northernProvinces } from "@/content/coverage";
import { roadProfiles } from "@/content/roads";
import { SubpageShell } from "@/components/site/subpage-shell";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, Questions, SafetyNote, Section } from "@/components/seo/landing-ui";
import { seoMetadata } from "@/seo/metadata";
export const metadata = seoMetadata({ title: "امداد خودرو شمال | گیلان، مازندران و گلستان", description: "امداد خودرو آنلاین شمال کشور در گیلان، مازندران و گلستان؛ شهرها و محورهای تحت پوشش، یدک‌کش و خودروبر، شرایط اعزام و استعلام هزینه.", path: "/شمال" });
export default function Page() {
 return <SubpageShell><LandingSchemas path="/شمال" title="امداد خودرو شمال کشور" description="شبکه هماهنگی خدمات خودرو در گیلان، مازندران و گلستان." collection /><LandingHeader title="امداد خودرو شمال؛ گیلان، مازندران و گلستان" intro="برای خرابی خودرو در سفر شمال، فقط نام استان کافی نیست. شهر، محور، جهت حرکت و محل دقیق توقف را اعلام کنید تا امداد در محل یا حمل مناسب هماهنگ شود. شبکه خودرو چاره در هر سه استان شمالی فعال است؛ امکان خدمت و زمان رسیدن به دسترسی، تجهیزات و ظرفیت همان درخواست بستگی دارد." crumbs={[{ label: "پوشش خدمات", href: "/coverage" }, { label: "شمال کشور" }]} /><AnswerBox><p>شماره هماهنگی امداد خودرو شمال، 09123022064 است. خدمات شامل بررسی خرابی، مکانیک سیار، باتری و تایر و حمل با یدک‌کش یا خودروبر متناسب است. نقاط خارج از بافت شهری، راه‌های فرعی و خدمات مکمل پیش از اعزام جداگانه بررسی می‌شوند؛ رسیدن در زمان ثابت یا ورود به هر مسیر وعده داده نمی‌شود.</p></AnswerBox><Section title="استان خود را انتخاب کنید"><LinkGrid links={northernProvinces.map((province) => ({ title: `امداد خودرو ${province.name}`, href: `/${province.slug}`, description: province.roads.join("، ") }))} /></Section>{northernProvinces.map((province) => <Section key={province.slug} title={`شهرهای ${province.name}`}><p>{province.planning}</p><LinkGrid links={allCities.filter((city) => city.province === province.slug).map((city) => ({ title: `امداد خودرو ${city.name}`, href: `/${city.slug}` }))} /></Section>)}<Section title="اگر در جاده متوقف شده‌اید"><p>جاده چالوس و آزادراه تهران–شمال دو مسیر متفاوت‌اند. نام محور، آخرین تونل یا خروجی و سمت حرکت را بگویید. در راه فرعی، فاصله تا جاده اصلی، عرض راه و سطح زمین برای انتخاب خودروبر اهمیت دارد.</p><LinkGrid links={roadProfiles.map((road) => ({ title: road.name, href: `/roads/${road.slug}` }))} /></Section><Questions items={[{ question: "آیا امداد در روستاها و مسیرهای فرعی شمال انجام می‌شود؟", answer: "درخواست با لوکیشن دقیق بررسی می‌شود. وضعیت راه، امکان استقرار تجهیزات، مجوز عبور و ظرفیت امدادگر تعیین‌کننده‌اند؛ پوشش استان به معنی تضمین دسترسی به هر نقطه نیست." }, { question: "آیا می‌توان خودرو را از شمال به تهران یا کرج حمل کرد؟", answer: "امکان حمل بین‌شهری با بررسی مدل و وضعیت خودرو، راه مجاز، مبدأ و مقصد و فضای تخلیه هماهنگ می‌شود. قیمت و شرایط قبل از بارگیری باید روشن شوند." }, { question: "آیا این مجموعه امداد رسمی خودروساز است؟", answer: "خیر. خودرو چاره شبکه مستقل هماهنگی خدمات خودرو است. در خودروی دارای گارانتی، شرایط تعمیر یا حمل را با ارائه‌دهنده ضمانت نیز کنترل کنید." }]} /><Section title="برنامه‌ریزی درخواست"><LinkGrid links={[{ title: "مراحل درخواست آنلاین", href: "/امداد-خودرو-آنلاین" }, { title: "قیمت و شرایط استعلام", href: "/pricing" }, { title: "خدمات برندهای خودرو", href: "/brands" }, { title: "امداد خودرو تهران", href: "/تهران" }, { title: "امداد خودرو کرج", href: "/کرج" }, { title: "اطلاعات تماس رسمی", href: "/contact" }]} /></Section><SafetyNote /><FinalContact /></SubpageShell>;
}
