import { notFound } from "next/navigation";
import { findRoad, roadProfiles } from "@/content/roads";
import { findCity } from "@/content/coverage";
import { SubpageShell } from "@/components/site/subpage-shell";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, Questions, SafetyNote, Section } from "@/components/seo/landing-ui";
import { seoMetadata } from "@/seo/metadata";
export const dynamicParams = false;
export function generateStaticParams() { return roadProfiles.map((road) => ({ slug: road.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const road = findRoad((await params).slug); if (!road) notFound(); return seoMetadata({ title: `امداد خودرو ${road.name} | راهنمای درخواست`, description: `امداد خودرو در ${road.name}؛ اعلام موقعیت و جهت حرکت، شرایط تعمیر در محل، حمل ایمن و استعلام هزینه و زمان اعزام.`, path: `/roads/${road.slug}` }); }
export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
 const road = findRoad((await params).slug); if (!road) notFound(); const path = `/roads/${road.slug}`;
 return <SubpageShell><LandingSchemas path={path} title={`امداد خودرو ${road.name}`} description={road.intro} crumbs={[{ name: "محورهای شمال", path: "/roads" }]} /><LandingHeader title={`امداد خودرو ${road.name}`} intro={road.intro} crumbs={[{ label: "محورهای شمال", href: "/roads" }, { label: road.name }]} /><AnswerBox><p>برای درخواست امداد در {road.name}، موقعیت دقیق و جهت حرکت را با شماره 09123022064 اعلام کنید. ظرفیت، راه دسترسی و روش حمل پیش از اعزام بررسی می‌شوند. برای مصدومیت یا خطر فوری، ابتدا خدمات اضطراری مسئول را مطلع کنید؛ این صفحه بازبودن راه را تضمین نمی‌کند.</p></AnswerBox><Section title="موقعیت را چگونه اعلام کنیم؟"><p>{road.location}</p><ul className="list-inside list-disc space-y-2">{road.checks.map((check) => <li key={check}>{check}</li>)}</ul></Section><Section title="ایمنی و محدودیت تعمیر کنار مسیر"><p>{road.risk}</p><p>در روشن‌نشدن خودرو، اطلاعات چراغ هشدار، نوع گیربکس و سابقه داغ‌شدن را آماده کنید. برای تایر آسیب‌دیده، وجود زاپاس و محل مناسب انجام کار بررسی می‌شود. تعهد به رسیدن در چند دقیقه بدون دانستن نقطه توقف و وضعیت راه قابل اتکا نیست.</p></Section><Section title="حمل خودرو و توافق هزینه"><p>{road.transport}</p><p>مبلغ توافق باید هزینه اعزام، مسافت حمل، بارگیری ویژه، عوارض و انتظار احتمالی را روشن کند. هزینه اضافه بدون توضیح نباید به‌عنوان بخشی نامعلوم از سفارش باقی بماند؛ قبل از شروع سؤال و رسید درخواست کنید.</p><LinkGrid links={[{ title: "قیمت خدمات و روش محاسبه", href: "/pricing" }, { title: "حمل خودرو اتوماتیک", href: "/blog/automatic-car-towing-guide" }, { title: "انتخاب یدک‌کش و خودروبر", href: "/امداد-خودرو" }]} /></Section><Questions items={[{ question: `آیا ${road.name} همین الان باز است؟`, answer: "این صفحه وضعیت زنده راه نیست. آخرین اطلاعیه‌های محدودیت و انسداد را از سامانه رسمی ۱۴۱ سازمان راهداری بررسی کنید." }, { question: "چه اطلاعاتی در تماس تلفنی مهم‌تر است؟", answer: road.location }, { question: "برای حمل خودرو به چه نکته‌ای توجه کنیم؟", answer: road.transport }]} /><Section title="شهرها و مسیرهای مرتبط"><LinkGrid links={[...road.cities.map((slug) => ({ title: `امداد خودرو ${findCity(slug)?.name ?? slug}`, href: `/${slug}` })), ...roadProfiles.filter((item) => item.slug !== road.slug).map((item) => ({ title: `راهنمای ${item.name}`, href: `/roads/${item.slug}` })), { title: "پوشش شمال کشور", href: "/شمال" }]} /></Section><SafetyNote /><FinalContact /></SubpageShell>;
}
