import type { MetadataRoute } from "next";
import { siteUrl } from "@/seo/metadata";

/**
 * robots.txt — the single place where crawl policy is decided.
 *
 * Two rules keep this file honest:
 *
 * 1. EXACTLY ONE `User-agent: *` group. The published robots.txt currently contains a
 *    second wildcard group injected by Cloudflare's "Managed robots" block, plus a
 *    duplicate set of AI-trainer blocks generated by the deployed app. RFC 9309 §2.2.1
 *    says matching groups MUST be merged and Google does merge groups that share a
 *    user-agent, but the outcome is crawler-dependent and Cloudflare's `Content-Signal`
 *    line only lives in the first group. Pick ONE owner for the AI policy — either here
 *    (then turn Cloudflare's managed robots off) or in Cloudflare (then keep this file
 *    limited to search crawlers) — and never both. See finding P1-5.
 *
 * 2. Separate "AI search" from "AI training". Blocking Google-Extended does not affect
 *    Google Search rankings (it only affects Gemini/Vertex training), and blocking GPTBot
 *    does not stop ChatGPT from citing the site as long as OAI-SearchBot is allowed.
 *    Answer engines that link back are referral traffic; trainers are not.
 */
const disallow = ["/api/"];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        // API routes hold no indexable content; the rest of the site is fully crawlable.
        disallow,
      },
      {
        userAgent: ["Googlebot", "Googlebot-Image", "Bingbot", "Slurp", "DuckDuckBot"],
        allow: "/",
        disallow,
      },
      {
        // AI answer engines that attribute and link back to the source.
        userAgent: ["OAI-SearchBot", "ChatGPT-User", "Claude-SearchBot", "Claude-User", "PerplexityBot", "Perplexity-User", "Applebot"],
        allow: "/",
        disallow,
      },
      {
        // AI training crawlers. Deliberately blocked; this is a business decision, not a
        // technical one, and it has no effect on Google Search rankings.
        userAgent: ["GPTBot", "Google-Extended", "ClaudeBot", "CCBot", "Bytespider", "Amazonbot", "meta-externalagent"],
        disallow: "/",
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
