import { notFound } from "next/navigation";
import { brandProfiles, findBrand } from "@/content/brands";
import { SubpageShell } from "@/components/site/subpage-shell";
import { seoMetadata } from "@/seo/metadata";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, PriceFactors, Questions, SafetyNote, Section } from "@/components/seo/landing-ui";
export const dynamicParams = false;
export function generateStaticParams() { return brandProfiles.map((brand) => ({ slug: brand.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const brand = findBrand((await params).slug); if (!brand) notFound();
  return seoMetadata({ title: `امداد خودرو ${brand.name} | حمل و خدمات در محل`, description: `امداد خودرو ${brand.name} در تهران، کرج و شمال؛ نکات عیب‌یابی، باتری، گیربکس و حمل ایمن با هماهنگی خدمات مستقل خودرو چاره.`, path: `/brands/${brand.slug}` });
}
export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const brand = findBrand((await params).slug); if (!brand) notFound(); const title = `امداد خودرو ${brand.name}`; const path = `/brands/${brand.slug}`;
  return <SubpageShell><LandingSchemas path={path} title={title} description={brand.intro} area="محدوده پوشش" crumbs={[{ name: "برندها", path: "/brands" }]} /><LandingHeader title={`${title}؛ خدمات در محل و حمل ایمن`} intro={brand.intro} crumbs={[{ label: "برندها", href: "/brands" }, { label: brand.name }]} /><AnswerBox><p>{title} در خودرو چاره با دریافت مدل و سال، نوع گیربکس و لوکیشن هماهنگ می‌شود. برای تهران، کرج، گیلان، مازندران و گلستان با 09123022064 تماس بگیرید. وجود قطعه و ابزار اختصاصی و امکان تعمیر پیش از اعزام بررسی می‌شود؛ خدمات مستقل است و جایگزین تعهدات گارانتی سازنده نیست.</p></AnswerBox><Section title={`مدل‌های ${brand.name} و اطلاعات لازم`}><p>نمونه‌های شناخته‌شده این برند: {brand.models.join("، ")}. این فهرست به معنی یکسان‌بودن مشخصات همه سال‌ها و تیپ‌ها یا تضمین موجودی قطعه نیست.</p><p>{brand.preparation}</p></Section><Section title={`عیب‌یابی و مکانیک سیار ${brand.name}`}><p>{brand.diagnosis}</p><p>تشخیص از راه دور اولیه است. حدود تعمیر در محل، نیاز به قطعه و هزینه باید بعد از ارزیابی مشخص شود؛ تعمیرات اساسی موتور و گیربکس در محیط کارگاهی انجام می‌شوند.</p></Section><Section title={`یدک‌کش یا خودروبر برای ${brand.name}؟`}><p>{brand.transport}</p><p>پیش از بارگیری از وضعیت بدنه و چرخ‌ها عکس بگیرید، وسایل شخصی را جمع کنید و آدرس تحویل را قطعی کنید. مجازبودن یک روش حمل باید با دفترچه همان مدل بررسی شود، نه توصیه عمومی برای کل برند.</p></Section><Section title={`باتری و برق ${brand.name}`}><p>{brand.electrical}</p></Section><PriceFactors area={`خدمات ${brand.name}`} /><Questions items={[{ question: `آیا خودرو چاره امداد رسمی ${brand.name} است؟`, answer: `خیر. خودرو چاره ارائه‌دهنده مستقل هماهنگی خدمات خودرو است و نمایندگی رسمی ${brand.name} نیست. برای خودروهای دارای گارانتی، شرایط را با ارائه‌دهنده ضمانت بررسی کنید.` }, { question: `برای حمل ${brand.name} چه اطلاعاتی لازم است؟`, answer: brand.transport }, { question: `آیا باتری‌به‌باتری برای همه مدل‌های ${brand.name} یکسان است؟`, answer: brand.electrical }, { question: "آیا موجودی قطعه و زمان اعزام تضمین می‌شود؟", answer: "خیر. مدل دقیق، قطعه یا دستگاه موردنیاز و محل توقف بررسی می‌شوند. ظرفیت و هزینه قبل از شروع هماهنگ خواهد شد؛ قیمت یا زمان ثابت برای تمام درخواست‌ها اعلام نمی‌شود." }]} /><Section title="خدمات، مناطق و راهنماهای مرتبط"><LinkGrid links={[{ title: `راهنمای مرتبط با ${brand.name}`, href: `/blog/${brand.guide}` }, { title: "مکانیک سیار", href: "/services/mobile-mechanic" }, { title: "خودروبر و کفی", href: "/services/flatbed-carrier" }, { title: "تست و تعویض باتری", href: "/services/battery-replacement" }, { title: "امداد خودرو تهران", href: "/تهران" }, { title: "امداد خودرو کرج", href: "/کرج" }, { title: "امداد خودرو شمال", href: "/شمال" }, { title: "مراحل درخواست آنلاین", href: "/امداد-خودرو-آنلاین" }, { title: "سایر برندهای خودرو", href: "/brands" }]} /></Section><SafetyNote /><FinalContact title={`هماهنگی امداد برای ${brand.name}`} /></SubpageShell>;
}
