import { SubpageShell } from "@/components/site/subpage-shell";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, Section } from "@/components/seo/landing-ui";
import { tools } from "@/content/tools";
import { seoMetadata } from "@/seo/metadata";
const title = "ابزارهای امداد خودرو؛ هزینه، انتخاب حمل و دیاگ";
export const metadata = seoMetadata({ title, description: "ابزارهای کاربردی خودرو چاره برای محاسبه و مقایسه هزینه حمل، انتخاب کفی یا یدک‌کش، بررسی اولیه نشانه خرابی و معنی کد دیاگ؛ بدون ارسال اطلاعات خودرو.", path: "/tools" });
export default function ToolsPage() {
  return <SubpageShell><LandingSchemas path="/tools" title={title} description="مجموعه ابزارهای کمک به تصمیم‌گیری پیش از هماهنگی امداد خودرو." collection /><LandingHeader primaryAction={{ label: "انتخاب ابزار", href: "#tool-list" }} title={title} intro="قبل از تماس، اطلاعات دقیق‌تری آماده کنید: روش حمل را بررسی کنید، شرح کد دیاگ را بخوانید و جمع برآوردهای دریافتی را کنترل کنید. این ابزارها در مرورگر کار می‌کنند؛ تشخیص قطعی، اعزام یا پرداخت انجام نمی‌دهند." crumbs={[{ label: "ابزارهای امداد خودرو" }]} /><AnswerBox updatedAt={{ iso: "2026-09-07", label: "۱۶ شهریور ۱۴۰۵" }}><p>برای موقعیت خطرناک، ابتدا خدمات اضطراری عمومی؛ برای انتخاب نوع کمک، راهنمای نشانه خرابی؛ برای حمل، بررسی مشخصات خودرو؛ و برای قیمت، فقط نرخ‌های اعلام‌شده به شما را وارد کنید. هیچ عدد رسمی، مسیر جاده‌ای یا ظرفیت لحظه‌ای در این ابزارها حدس زده نمی‌شود.</p></AnswerBox><Section id="tool-list" title="ابزار متناسب با نیازتان را انتخاب کنید"><LinkGrid label="ابزارهای کاربردی" links={[{ title: "محاسبه هزینه حمل با کفی و یدک‌کش", href: "/pricing#calculator", description: "جمع نرخ پایه، مسافت توافق‌شده، انتظار و هزینه‌های جدا" }, { title: "مقایسه دو برآورد هزینه حمل", href: "/pricing#compare-quotes", description: "کنترل دو رقم هم‌دامنه؛ نه مقایسه کیفیت یا تضمین قیمت بازار" }, ...tools.map((tool) => ({ title: tool.title, href: `/tools/${tool.slug}`, description: tool.description }))]} /></Section><Section title="چرا نتیجه ابزار با تأیید خدمت فرق دارد؟"><p>فرم محاسباتی فقط از انتخاب‌ها و عددهایی استفاده می‌کند که خودتان وارد کرده‌اید. وضعیت واقعی چرخ، محل توقف، مدارهای خودرو و اعتبار برآورد از راه دور تأیید نمی‌شوند. پس از آماده‌شدن اطلاعات، نوع خدمت و هزینه را با اپراتور هماهنگ کنید؛ هیچ‌کدام از این ابزارها سفارش ثبت نمی‌کنند.</p><p>ابزارها به نام، شماره تماس یا نشانی دقیق شما نیاز ندارند. ورودی‌ها در URL یا ذخیره‌سازی دائمی مرورگر قرار نمی‌گیرند. تنها رویداد استفاده از ابزار، بدون مقدار فیلدها، می‌تواند در آمار استفاده سایت ثبت شود.</p></Section><Section title="راهنماهای تکمیلی"><LinkGrid links={[{ title: "امداد خودرو و انتخاب خدمت", href: "/امداد-خودرو" }, { title: "امداد خودرو آنلاین و مراحل هماهنگی", href: "/امداد-خودرو-آنلاین" }, { title: "چک‌لیست تحویل خودرو به خودروبر", href: "/blog/flatbed-handover-checklist" }, { title: "مقالات ایمنی و نگهداری خودرو", href: "/blog" }]} /></Section><FinalContact /></SubpageShell>;
}
