import { SubpageShell } from "@/components/site/subpage-shell";
import { brandProfiles } from "@/content/brands";
import { seoMetadata } from "@/seo/metadata";
import { itemListSchema } from "@/seo/schemas";
import { StructuredData } from "@/components/seo/structured-data";
import { AnswerBox, FinalContact, LandingHeader, LandingSchemas, LinkGrid, SafetyNote, Section } from "@/components/seo/landing-ui";
export const metadata = seoMetadata({ title: "امداد خودرو برندهای ایرانی و خارجی", description: "راهنمای امداد خودرو برای ایران خودرو، سایپا، تویوتا و برندهای دیگر؛ تفاوت مدل و گیربکس، باتری، حمل ایمن و هماهنگی خدمات مستقل خودرو چاره.", path: "/brands" });
export default function Page() {
  return <SubpageShell><LandingSchemas path="/brands" title="امداد خودرو برای برندهای ایرانی و خارجی" description="انتخاب خدمات متناسب با مدل خودرو و وضعیت واقعی خرابی." collection /><StructuredData data={itemListSchema({ name: "برندهای خودرو", path: "/brands", items: brandProfiles.map((brand) => ({ name: brand.name, path: `/brands/${brand.slug}` })) })} /><LandingHeader title="امداد خودرو برای برندهای ایرانی و خارجی" intro="مدل، سال ساخت، گیربکس و انتقال قدرت خودرو تعیین می‌کنند چه ابزار و روش حملی مناسب است. از صفحه برند شروع کنید و هنگام هماهنگی، مشخصات دقیق همان خودرو را اعلام کنید؛ نام برند به‌تنهایی برای انتخاب قطعه یا یدک‌کش کافی نیست." crumbs={[{ label: "برندهای خودرو" }]} /><AnswerBox><p>خودرو چاره خدمات مستقل امداد خودرو را در تهران، کرج، گیلان، مازندران و گلستان هماهنگ می‌کند. استفاده از نام برندها برای معرفی خودروهای قابل بررسی است؛ این مجموعه نمایندگی رسمی خودروسازان نیست. برای خودروهای دارای گارانتی، شرایط تعمیر و حمل را با ارائه‌دهنده ضمانت نیز کنترل کنید.</p></AnswerBox><Section title="برند خودرو را انتخاب کنید"><LinkGrid links={brandProfiles.map((brand) => ({ title: `امداد خودرو ${brand.name}`, href: `/brands/${brand.slug}`, description: brand.models.join("، ") }))} /></Section><Section title="برای خودروی خاص چه اطلاعاتی لازم است؟"><p>مدل و تیپ کامل، سال، نوع گیربکس، وجود سامانه چهارچرخ محرک، هیبریدی یا برقی‌بودن و وضعیت قفل چرخ‌ها را بگویید. موجودبودن قطعه یا دستگاه اختصاصی برای هر مدل پیش از اعزام بررسی می‌شود و از روی فهرست این صفحه نباید تضمین موجودی برداشت کرد.</p><LinkGrid links={[{ title: "پوشش شهرها و استان‌ها", href: "/coverage" }, { title: "قیمت و شرایط استعلام", href: "/pricing" }, { title: "حمل خودرو اتوماتیک", href: "/blog/automatic-car-towing-guide" }]} /></Section><SafetyNote /><FinalContact /></SubpageShell>;
}
